### ISSUE TITLE
Add support for System.IServiceProvider

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Giraffe.GoodRead#3]
Currently GoodRead only works with `HttpContext`, so this library can't be used for cases where we only have a `System.IServiceProvider`. `HttpContext` interfaces `System.IServiceProvider`, so it would be nice to make the types flexible (`#System.IServiceProvider`), then do type testing to see if it's an `HttpContext` and then only apply the GUID checks for that case.

The main motivation for this is so this library can be used with [Fable.SignalR](https://github.com/Shmew/Fable.SignalR), which while you can access a `HttpContext`, that is only available with certain transport types, so it isn't reliable. Which means I have to inject a `System.IServiceProvider` instead.

Let me know if you don't have the cycles to do this, I don't mind submitting a PR if so.

**Comment by Zaid-Ajaj** [comment]
Hi Cody, I don't really get the problem. Can you please elaborate? If `IServiceProvider` is itself a framework provided service, then you should be able to require it like any other dependency such as `ILogger` or `IConfiguration`

> I don't mind submitting a PR if so.

These are always welcome, though I just want to make sure we don't add things that are not needed :smile:

**Comment by Shmew** [comment]
Yeah it's perhaps not really suitable for this repo. I guess all I'm really wanting is a reader for `System.IServiceProvider`, which doesn't necessarily fit in here. Sorry to waste your time 😓
